CREATE TABLE [dbo].[tblGame]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Player1] UNIQUEIDENTIFIER NOT NULL, 
    [Player2] UNIQUEIDENTIFIER NOT NULL, 
    [WinnerId] UNIQUEIDENTIFIER NOT NULL, 
    [LoserId] UNIQUEIDENTIFIER NOT NULL, 
    [StartTime] TIME NOT NULL, 
    [EndTime] TIME NOT NULL, 
    [IsOver] INT NOT NULL, 
    [GameId] INT NOT NULL
)
