// <auto-generated />
using System;
using HiddenBattleship.PL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiddenBattleship.PL.Migrations
{
    [DbContext(typeof(HiddenBattleshipEntities))]
    [Migration("20231204111640_createdatabase")]
    partial class createdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblChatHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChatHistoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("Receiver")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Sender")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Timestamp")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__tblChatH__3214EC07CBD56E82");

                    b.HasIndex("GameId");

                    b.HasIndex("Receiver");

                    b.ToTable("tblChatHistory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b458db6c-93cb-4612-a6a7-129b4382a265"),
                            ChatHistoryId = 1,
                            GameId = new Guid("c9731145-2bab-44a6-b3c9-c04c2de638d7"),
                            Message = "1v1 me",
                            Receiver = new Guid("2c8a9bf5-b85e-4806-bff7-ebb67c96a1c4"),
                            Sender = new Guid("d7fc902a-8e8b-411f-ab57-79b60cb0e676"),
                            Timestamp = new TimeSpan(0, 4, 10, 55, 0)
                        },
                        new
                        {
                            Id = new Guid("ffaf3f06-a655-436d-b013-e582fa5a15df"),
                            ChatHistoryId = 1,
                            GameId = new Guid("c9731145-2bab-44a6-b3c9-c04c2de638d7"),
                            Message = "You missed, LOL",
                            Receiver = new Guid("d7fc902a-8e8b-411f-ab57-79b60cb0e676"),
                            Sender = new Guid("2c8a9bf5-b85e-4806-bff7-ebb67c96a1c4"),
                            Timestamp = new TimeSpan(0, 5, 1, 20, 0)
                        },
                        new
                        {
                            Id = new Guid("d950b146-80e7-4eea-8ace-d908fdc4538b"),
                            ChatHistoryId = 1,
                            GameId = new Guid("c9731145-2bab-44a6-b3c9-c04c2de638d7"),
                            Message = "Follow my twitch stream?",
                            Receiver = new Guid("2c8a9bf5-b85e-4806-bff7-ebb67c96a1c4"),
                            Sender = new Guid("d7fc902a-8e8b-411f-ab57-79b60cb0e676"),
                            Timestamp = new TimeSpan(0, 11, 51, 14, 0)
                        },
                        new
                        {
                            Id = new Guid("fb765900-433c-41d1-87dd-357f1963782d"),
                            ChatHistoryId = 1,
                            GameId = new Guid("c9731145-2bab-44a6-b3c9-c04c2de638d7"),
                            Message = "You're hacking, i'm telling my dad he works at Jagex!!11!",
                            Receiver = new Guid("d7fc902a-8e8b-411f-ab57-79b60cb0e676"),
                            Sender = new Guid("2c8a9bf5-b85e-4806-bff7-ebb67c96a1c4"),
                            Timestamp = new TimeSpan(0, 1, 28, 19, 0)
                        },
                        new
                        {
                            Id = new Guid("51cdedf4-7b5c-4a8f-9da5-1940e5e43fc4"),
                            ChatHistoryId = 2,
                            GameId = new Guid("2c61ed53-9f16-4ef0-8133-4e01870346b0"),
                            Message = "1v1 me",
                            Receiver = new Guid("2c8a9bf5-b85e-4806-bff7-ebb67c96a1c4"),
                            Sender = new Guid("bd41a2ea-d599-49bb-853d-5776a6aae471"),
                            Timestamp = new TimeSpan(0, 4, 10, 55, 0)
                        },
                        new
                        {
                            Id = new Guid("25a10537-12ec-4bb0-8e09-d73a6a3c6b3d"),
                            ChatHistoryId = 2,
                            GameId = new Guid("2c61ed53-9f16-4ef0-8133-4e01870346b0"),
                            Message = "You missed, LOL",
                            Receiver = new Guid("bd41a2ea-d599-49bb-853d-5776a6aae471"),
                            Sender = new Guid("2c8a9bf5-b85e-4806-bff7-ebb67c96a1c4"),
                            Timestamp = new TimeSpan(0, 5, 1, 20, 0)
                        },
                        new
                        {
                            Id = new Guid("7ec38e9b-5c80-4e2d-b602-24a3c4c5ec12"),
                            ChatHistoryId = 2,
                            GameId = new Guid("2c61ed53-9f16-4ef0-8133-4e01870346b0"),
                            Message = "Follow my twitch stream?",
                            Receiver = new Guid("2c8a9bf5-b85e-4806-bff7-ebb67c96a1c4"),
                            Sender = new Guid("bd41a2ea-d599-49bb-853d-5776a6aae471"),
                            Timestamp = new TimeSpan(0, 11, 51, 14, 0)
                        },
                        new
                        {
                            Id = new Guid("9811ebd6-1387-409b-a0df-ab986444f4b5"),
                            ChatHistoryId = 2,
                            GameId = new Guid("2c61ed53-9f16-4ef0-8133-4e01870346b0"),
                            Message = "You're hacking, i'm telling my dad he works at Jagex!!11!",
                            Receiver = new Guid("bd41a2ea-d599-49bb-853d-5776a6aae471"),
                            Sender = new Guid("2c8a9bf5-b85e-4806-bff7-ebb67c96a1c4"),
                            Timestamp = new TimeSpan(0, 1, 28, 19, 0)
                        },
                        new
                        {
                            Id = new Guid("b51105a2-993a-4c23-adda-f10a4ac8a534"),
                            ChatHistoryId = 3,
                            GameId = new Guid("de1e8857-8e5e-44f6-b5e5-a5f9333dec4b"),
                            Message = "1v1 me",
                            Receiver = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f"),
                            Sender = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f"),
                            Timestamp = new TimeSpan(0, 4, 10, 55, 0)
                        },
                        new
                        {
                            Id = new Guid("202acd67-b2e4-41d0-9163-83c603d51779"),
                            ChatHistoryId = 3,
                            GameId = new Guid("de1e8857-8e5e-44f6-b5e5-a5f9333dec4b"),
                            Message = "You missed, LOL",
                            Receiver = new Guid("2c8a9bf5-b85e-4806-bff7-ebb67c96a1c4"),
                            Sender = new Guid("2c8a9bf5-b85e-4806-bff7-ebb67c96a1c4"),
                            Timestamp = new TimeSpan(0, 5, 1, 20, 0)
                        },
                        new
                        {
                            Id = new Guid("7f074d26-dd20-4b29-a179-941d3f4b93cc"),
                            ChatHistoryId = 3,
                            GameId = new Guid("de1e8857-8e5e-44f6-b5e5-a5f9333dec4b"),
                            Message = "Follow my twitch stream?",
                            Receiver = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f"),
                            Sender = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f"),
                            Timestamp = new TimeSpan(0, 11, 51, 14, 0)
                        },
                        new
                        {
                            Id = new Guid("c27ef319-964b-41ab-a2f9-6ca8e2dd8672"),
                            ChatHistoryId = 3,
                            GameId = new Guid("de1e8857-8e5e-44f6-b5e5-a5f9333dec4b"),
                            Message = "You're hacking, i'm telling my dad he works at Jagex!!11!",
                            Receiver = new Guid("2c8a9bf5-b85e-4806-bff7-ebb67c96a1c4"),
                            Sender = new Guid("2c8a9bf5-b85e-4806-bff7-ebb67c96a1c4"),
                            Timestamp = new TimeSpan(0, 1, 28, 19, 0)
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("EndTime")
                        .IsRequired()
                        .HasColumnType("time");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOver")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LoserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Player1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Player2")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("tblChatHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__tblGame__3214EC07DA24F9C4");

                    b.HasIndex("LoserId");

                    b.HasIndex("tblChatHistoryId");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9731145-2bab-44a6-b3c9-c04c2de638d7"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 0,
                            IsOver = true,
                            LoserId = new Guid("d7fc902a-8e8b-411f-ab57-79b60cb0e676"),
                            Player1 = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f"),
                            Player2 = new Guid("d7fc902a-8e8b-411f-ab57-79b60cb0e676"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f")
                        },
                        new
                        {
                            Id = new Guid("2c61ed53-9f16-4ef0-8133-4e01870346b0"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 1,
                            IsOver = false,
                            LoserId = new Guid("d7fc902a-8e8b-411f-ab57-79b60cb0e676"),
                            Player1 = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f"),
                            Player2 = new Guid("d7fc902a-8e8b-411f-ab57-79b60cb0e676"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f")
                        },
                        new
                        {
                            Id = new Guid("de1e8857-8e5e-44f6-b5e5-a5f9333dec4b"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 2,
                            IsOver = false,
                            LoserId = new Guid("d7fc902a-8e8b-411f-ab57-79b60cb0e676"),
                            Player1 = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f"),
                            Player2 = new Guid("d7fc902a-8e8b-411f-ab57-79b60cb0e676"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f")
                        },
                        new
                        {
                            Id = new Guid("e945baf2-fbfb-4d49-87cd-9627a2525ee0"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 3,
                            IsOver = false,
                            LoserId = new Guid("d7fc902a-8e8b-411f-ab57-79b60cb0e676"),
                            Player1 = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f"),
                            Player2 = new Guid("d7fc902a-8e8b-411f-ab57-79b60cb0e676"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f")
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGameMove", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GameMoveId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHit")
                        .HasColumnType("bit");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetCoordinates")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeSpan>("TimeStamp")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__tblGameM__3214EC07B921B560");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tblGameMove", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c5c348d-188d-4858-b615-e79dbb19fb37"),
                            GameId = new Guid("c9731145-2bab-44a6-b3c9-c04c2de638d7"),
                            GameMoveId = 0,
                            IsHit = true,
                            PlayerId = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("5ba4fb22-c8a4-4a50-995f-d333af8f76d4"),
                            GameId = new Guid("c9731145-2bab-44a6-b3c9-c04c2de638d7"),
                            GameMoveId = 1,
                            IsHit = true,
                            PlayerId = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("78fc66e1-6769-490b-9b2b-0d245f1b52b2"),
                            GameId = new Guid("c9731145-2bab-44a6-b3c9-c04c2de638d7"),
                            GameMoveId = 2,
                            IsHit = true,
                            PlayerId = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("02d140fd-1f51-4276-b9d0-c68264a74669"),
                            GameId = new Guid("c9731145-2bab-44a6-b3c9-c04c2de638d7"),
                            GameMoveId = 3,
                            IsHit = true,
                            PlayerId = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__tblPlaye__3214EC0786DA1BDC");

                    b.ToTable("tblPlayer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("835b7b7a-872e-4475-9f5c-2965995af13f"),
                            Email = "123@gmail.com",
                            Password = "W6ph5Mm5Pz8GgiULbPgzG37mj9g=",
                            UserName = "Sh1PD3STR0Y3R"
                        },
                        new
                        {
                            Id = new Guid("d7fc902a-8e8b-411f-ab57-79b60cb0e676"),
                            Email = "456@gmail.com",
                            Password = "YRfkWrV/hmDYZqIcpenSwx28GUU=",
                            UserName = "Timmy"
                        },
                        new
                        {
                            Id = new Guid("2c8a9bf5-b85e-4806-bff7-ebb67c96a1c4"),
                            Email = "789@yahoo.com",
                            Password = "7DUut/wAuxmp4mKiKKNr9eEUeG0=",
                            UserName = "LoveMyCats1155"
                        },
                        new
                        {
                            Id = new Guid("bd41a2ea-d599-49bb-853d-5776a6aae471"),
                            Email = "aaabbb@amazon.com",
                            Password = "3oUt/zAHVa53n7yyDzprXz4Rxs8=",
                            UserName = "Skeert"
                        },
                        new
                        {
                            Id = new Guid("ce915408-18c5-47a4-a1ca-d0aad6865cfe"),
                            Email = "uTest@yahoo.com",
                            Password = "qUqP5cyxm6YcTAhz05Hph5gvu9M=",
                            UserName = "uTest"
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblChatHistory", b =>
                {
                    b.HasOne("HiddenBattleship.PL.Entities.tblGame", "Game")
                        .WithMany("tblChatHistories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiddenBattleship.PL.Entities.tblPlayer", "Player")
                        .WithMany("tblChatHistories")
                        .HasForeignKey("Receiver")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGame", b =>
                {
                    b.HasOne("HiddenBattleship.PL.Entities.tblPlayer", "Player")
                        .WithMany("tblGames")
                        .HasForeignKey("LoserId");

                    b.HasOne("HiddenBattleship.PL.Entities.tblChatHistory", null)
                        .WithMany("tblGames")
                        .HasForeignKey("tblChatHistoryId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGameMove", b =>
                {
                    b.HasOne("HiddenBattleship.PL.Entities.tblGame", "Game")
                        .WithMany("tblGameMoves")
                        .HasForeignKey("GameId")
                        .IsRequired();

                    b.HasOne("HiddenBattleship.PL.Entities.tblPlayer", "Player")
                        .WithMany("tblGameMoves")
                        .HasForeignKey("PlayerId")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblChatHistory", b =>
                {
                    b.Navigation("tblGames");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGame", b =>
                {
                    b.Navigation("tblChatHistories");

                    b.Navigation("tblGameMoves");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblPlayer", b =>
                {
                    b.Navigation("tblChatHistories");

                    b.Navigation("tblGameMoves");

                    b.Navigation("tblGames");
                });
#pragma warning restore 612, 618
        }
    }
}
