// <auto-generated />
using System;
using HiddenBattleship.PL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiddenBattleship.PL.Migrations
{
    [DbContext(typeof(HiddenBattleshipEntities))]
    [Migration("20231124190615_DBchange")]
    partial class DBchange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblChatHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChatHistoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("Receiver")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Sender")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Timestamp")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__tblChatH__3214EC07CBD56E82");

                    b.HasIndex("GameId");

                    b.HasIndex("Receiver");

                    b.ToTable("tblChatHistory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb4972d2-4bf4-43e9-9cec-55049dcd7288"),
                            ChatHistoryId = 0,
                            GameId = new Guid("9e227195-3ea1-4d23-a5fc-df835b7c46a8"),
                            Message = "1v1 me",
                            Receiver = new Guid("2ada9df8-3d6d-4116-8d71-f4ce4f6cd2d3"),
                            Sender = new Guid("0e7af0f1-d3b4-4d3f-aab7-5399cba2868a"),
                            Timestamp = new TimeSpan(0, 4, 10, 55, 0)
                        },
                        new
                        {
                            Id = new Guid("ce22de26-5736-4eca-89e0-3c4aeb6c7f0e"),
                            ChatHistoryId = 1,
                            GameId = new Guid("9e227195-3ea1-4d23-a5fc-df835b7c46a8"),
                            Message = "You missed, LOL",
                            Receiver = new Guid("0e7af0f1-d3b4-4d3f-aab7-5399cba2868a"),
                            Sender = new Guid("2ada9df8-3d6d-4116-8d71-f4ce4f6cd2d3"),
                            Timestamp = new TimeSpan(0, 5, 1, 20, 0)
                        },
                        new
                        {
                            Id = new Guid("810d03b7-fa50-485c-9304-8a657c72b547"),
                            ChatHistoryId = 2,
                            GameId = new Guid("a7235228-a0fd-45a8-ad74-15d904016984"),
                            Message = "Follow my twitch stream?",
                            Receiver = new Guid("8be96ee1-3dfd-4621-87aa-696515e526e4"),
                            Sender = new Guid("2ada9df8-3d6d-4116-8d71-f4ce4f6cd2d3"),
                            Timestamp = new TimeSpan(0, 11, 51, 14, 0)
                        },
                        new
                        {
                            Id = new Guid("7874c4ec-c337-4362-9d01-ef3bb31d96d0"),
                            ChatHistoryId = 3,
                            GameId = new Guid("2c4084fc-7a70-4fc9-a411-f79aa6c5e4bf"),
                            Message = "You're hacking, i'm telling my dad he works at Jagex!!11!",
                            Receiver = new Guid("0e7af0f1-d3b4-4d3f-aab7-5399cba2868a"),
                            Sender = new Guid("8be96ee1-3dfd-4621-87aa-696515e526e4"),
                            Timestamp = new TimeSpan(0, 1, 28, 19, 0)
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOver")
                        .HasColumnType("bit");

                    b.Property<Guid>("LoserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Player1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Player2")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("tblChatHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__tblGame__3214EC07DA24F9C4");

                    b.HasIndex("LoserId");

                    b.HasIndex("tblChatHistoryId");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e227195-3ea1-4d23-a5fc-df835b7c46a8"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 0,
                            IsOver = true,
                            LoserId = new Guid("2ada9df8-3d6d-4116-8d71-f4ce4f6cd2d3"),
                            Player1 = new Guid("5ef72535-3891-4689-b1d6-281649d31e59"),
                            Player2 = new Guid("2ada9df8-3d6d-4116-8d71-f4ce4f6cd2d3"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("5ef72535-3891-4689-b1d6-281649d31e59")
                        },
                        new
                        {
                            Id = new Guid("a7235228-a0fd-45a8-ad74-15d904016984"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 1,
                            IsOver = false,
                            LoserId = new Guid("2ada9df8-3d6d-4116-8d71-f4ce4f6cd2d3"),
                            Player1 = new Guid("5ef72535-3891-4689-b1d6-281649d31e59"),
                            Player2 = new Guid("2ada9df8-3d6d-4116-8d71-f4ce4f6cd2d3"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("5ef72535-3891-4689-b1d6-281649d31e59")
                        },
                        new
                        {
                            Id = new Guid("2c4084fc-7a70-4fc9-a411-f79aa6c5e4bf"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 2,
                            IsOver = false,
                            LoserId = new Guid("2ada9df8-3d6d-4116-8d71-f4ce4f6cd2d3"),
                            Player1 = new Guid("5ef72535-3891-4689-b1d6-281649d31e59"),
                            Player2 = new Guid("2ada9df8-3d6d-4116-8d71-f4ce4f6cd2d3"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("5ef72535-3891-4689-b1d6-281649d31e59")
                        },
                        new
                        {
                            Id = new Guid("cec32b6c-024a-4186-917b-892f2c443d64"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 3,
                            IsOver = false,
                            LoserId = new Guid("2ada9df8-3d6d-4116-8d71-f4ce4f6cd2d3"),
                            Player1 = new Guid("5ef72535-3891-4689-b1d6-281649d31e59"),
                            Player2 = new Guid("2ada9df8-3d6d-4116-8d71-f4ce4f6cd2d3"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("5ef72535-3891-4689-b1d6-281649d31e59")
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGameMove", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GameMoveId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHit")
                        .HasColumnType("bit");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetCoordinates")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeSpan>("TimeStamp")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__tblGameM__3214EC07B921B560");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tblGameMove", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc70191c-2899-45b4-b2d0-2e983008aafc"),
                            GameId = new Guid("9e227195-3ea1-4d23-a5fc-df835b7c46a8"),
                            GameMoveId = 0,
                            IsHit = true,
                            PlayerId = new Guid("5ef72535-3891-4689-b1d6-281649d31e59"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("e4a5fe2a-b9a2-42d5-b9dd-e542fd007c15"),
                            GameId = new Guid("9e227195-3ea1-4d23-a5fc-df835b7c46a8"),
                            GameMoveId = 1,
                            IsHit = true,
                            PlayerId = new Guid("5ef72535-3891-4689-b1d6-281649d31e59"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("3927c5fe-7dab-4426-b0de-37b8297ce886"),
                            GameId = new Guid("9e227195-3ea1-4d23-a5fc-df835b7c46a8"),
                            GameMoveId = 2,
                            IsHit = true,
                            PlayerId = new Guid("5ef72535-3891-4689-b1d6-281649d31e59"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("7b2b6c47-fef8-40bf-b4e1-1f3b3ec6b82b"),
                            GameId = new Guid("9e227195-3ea1-4d23-a5fc-df835b7c46a8"),
                            GameMoveId = 3,
                            IsHit = true,
                            PlayerId = new Guid("5ef72535-3891-4689-b1d6-281649d31e59"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__tblPlaye__3214EC0786DA1BDC");

                    b.ToTable("tblPlayer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ef72535-3891-4689-b1d6-281649d31e59"),
                            Email = "123@gmail.com",
                            Password = "W6ph5Mm5Pz8GgiULbPgzG37mj9g=",
                            UserName = "Sh1PD3STR0Y3R"
                        },
                        new
                        {
                            Id = new Guid("2ada9df8-3d6d-4116-8d71-f4ce4f6cd2d3"),
                            Email = "456@gmail.com",
                            Password = "YRfkWrV/hmDYZqIcpenSwx28GUU=",
                            UserName = "Timmy"
                        },
                        new
                        {
                            Id = new Guid("8be96ee1-3dfd-4621-87aa-696515e526e4"),
                            Email = "789@yahoo.com",
                            Password = "7DUut/wAuxmp4mKiKKNr9eEUeG0=",
                            UserName = "LoveMyCats1155"
                        },
                        new
                        {
                            Id = new Guid("0e7af0f1-d3b4-4d3f-aab7-5399cba2868a"),
                            Email = "aaabbb@amazon.com",
                            Password = "3oUt/zAHVa53n7yyDzprXz4Rxs8=",
                            UserName = "Skeert"
                        },
                        new
                        {
                            Id = new Guid("0d47950d-e192-47eb-bd01-0015a6d6e1ee"),
                            Email = "uTest@yahoo.com",
                            Password = "qUqP5cyxm6YcTAhz05Hph5gvu9M=",
                            UserName = "uTest"
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblChatHistory", b =>
                {
                    b.HasOne("HiddenBattleship.PL.Entities.tblGame", "Game")
                        .WithMany("tblChatHistories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiddenBattleship.PL.Entities.tblPlayer", "Player")
                        .WithMany("tblChatHistories")
                        .HasForeignKey("Receiver")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGame", b =>
                {
                    b.HasOne("HiddenBattleship.PL.Entities.tblPlayer", "Player")
                        .WithMany("tblGames")
                        .HasForeignKey("LoserId")
                        .IsRequired();

                    b.HasOne("HiddenBattleship.PL.Entities.tblChatHistory", null)
                        .WithMany("tblGames")
                        .HasForeignKey("tblChatHistoryId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGameMove", b =>
                {
                    b.HasOne("HiddenBattleship.PL.Entities.tblGame", "Game")
                        .WithMany("tblGameMoves")
                        .HasForeignKey("GameId")
                        .IsRequired();

                    b.HasOne("HiddenBattleship.PL.Entities.tblPlayer", "Player")
                        .WithMany("tblGameMoves")
                        .HasForeignKey("PlayerId")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblChatHistory", b =>
                {
                    b.Navigation("tblGames");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGame", b =>
                {
                    b.Navigation("tblChatHistories");

                    b.Navigation("tblGameMoves");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblPlayer", b =>
                {
                    b.Navigation("tblChatHistories");

                    b.Navigation("tblGameMoves");

                    b.Navigation("tblGames");
                });
#pragma warning restore 612, 618
        }
    }
}
