// <auto-generated />
using System;
using HiddenBattleship.PL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiddenBattleship.PL.Migrations
{
    [DbContext(typeof(HiddenBattleshipEntities))]
    partial class HiddenBattleshipEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblChatHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChatHistoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("Receiver")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Sender")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Timestamp")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__tblChatH__3214EC07CBD56E82");

                    b.HasIndex("GameId");

                    b.HasIndex("Receiver");

                    b.ToTable("tblChatHistory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3652d676-6d27-4f37-85ae-1111b6815728"),
                            ChatHistoryId = 0,
                            GameId = new Guid("f2932938-3b6d-45b9-8de0-f623a51c13e2"),
                            Message = "1v1 me",
                            Receiver = new Guid("f730d22c-1ad2-452c-92cc-d82ce3826c41"),
                            Sender = new Guid("337455fa-8b86-44b3-9086-0aae72e9c108"),
                            Timestamp = new TimeSpan(0, 4, 10, 55, 0)
                        },
                        new
                        {
                            Id = new Guid("5b10a02d-fde7-4fad-aeda-556ca03d314e"),
                            ChatHistoryId = 1,
                            GameId = new Guid("f2932938-3b6d-45b9-8de0-f623a51c13e2"),
                            Message = "You missed, LOL",
                            Receiver = new Guid("337455fa-8b86-44b3-9086-0aae72e9c108"),
                            Sender = new Guid("f730d22c-1ad2-452c-92cc-d82ce3826c41"),
                            Timestamp = new TimeSpan(0, 5, 1, 20, 0)
                        },
                        new
                        {
                            Id = new Guid("fc441581-4c59-4be3-bee4-dca76a4819f2"),
                            ChatHistoryId = 2,
                            GameId = new Guid("23efe435-0fb2-499c-a816-d0b969951408"),
                            Message = "Follow my twitch stream?",
                            Receiver = new Guid("b2367ccb-adf4-418a-9c8b-67b24ce6c968"),
                            Sender = new Guid("f730d22c-1ad2-452c-92cc-d82ce3826c41"),
                            Timestamp = new TimeSpan(0, 11, 51, 14, 0)
                        },
                        new
                        {
                            Id = new Guid("d9a440e3-6b4f-42e4-b78b-7e13ba488170"),
                            ChatHistoryId = 3,
                            GameId = new Guid("edbb4462-761e-4479-881a-009e332cdb57"),
                            Message = "You're hacking, i'm telling my dad he works at Jagex!!11!",
                            Receiver = new Guid("337455fa-8b86-44b3-9086-0aae72e9c108"),
                            Sender = new Guid("b2367ccb-adf4-418a-9c8b-67b24ce6c968"),
                            Timestamp = new TimeSpan(0, 1, 28, 19, 0)
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("IsOver")
                        .HasColumnType("int");

                    b.Property<Guid>("LoserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Player1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Player2")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("tblChatHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__tblGame__3214EC07DA24F9C4");

                    b.HasIndex("LoserId");

                    b.HasIndex("tblChatHistoryId");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2932938-3b6d-45b9-8de0-f623a51c13e2"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 0,
                            IsOver = 0,
                            LoserId = new Guid("f730d22c-1ad2-452c-92cc-d82ce3826c41"),
                            Player1 = new Guid("3054955c-8301-46c6-97ab-776108ef0a31"),
                            Player2 = new Guid("f730d22c-1ad2-452c-92cc-d82ce3826c41"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("3054955c-8301-46c6-97ab-776108ef0a31")
                        },
                        new
                        {
                            Id = new Guid("23efe435-0fb2-499c-a816-d0b969951408"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 1,
                            IsOver = 0,
                            LoserId = new Guid("f730d22c-1ad2-452c-92cc-d82ce3826c41"),
                            Player1 = new Guid("3054955c-8301-46c6-97ab-776108ef0a31"),
                            Player2 = new Guid("f730d22c-1ad2-452c-92cc-d82ce3826c41"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("3054955c-8301-46c6-97ab-776108ef0a31")
                        },
                        new
                        {
                            Id = new Guid("edbb4462-761e-4479-881a-009e332cdb57"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 2,
                            IsOver = 0,
                            LoserId = new Guid("f730d22c-1ad2-452c-92cc-d82ce3826c41"),
                            Player1 = new Guid("3054955c-8301-46c6-97ab-776108ef0a31"),
                            Player2 = new Guid("f730d22c-1ad2-452c-92cc-d82ce3826c41"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("3054955c-8301-46c6-97ab-776108ef0a31")
                        },
                        new
                        {
                            Id = new Guid("7ffbb846-8a6e-47f0-8ec8-851c95bb82af"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 3,
                            IsOver = 0,
                            LoserId = new Guid("f730d22c-1ad2-452c-92cc-d82ce3826c41"),
                            Player1 = new Guid("3054955c-8301-46c6-97ab-776108ef0a31"),
                            Player2 = new Guid("f730d22c-1ad2-452c-92cc-d82ce3826c41"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("3054955c-8301-46c6-97ab-776108ef0a31")
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGameMove", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GameMoveId")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetCoordinates")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeSpan>("TimeStamp")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__tblGameM__3214EC07B921B560");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tblGameMove", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2974d4f8-32e9-4cb1-99d2-ffb00725a326"),
                            GameId = new Guid("f2932938-3b6d-45b9-8de0-f623a51c13e2"),
                            GameMoveId = 0,
                            PlayerId = new Guid("3054955c-8301-46c6-97ab-776108ef0a31"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("b138605a-4eca-492d-8609-962b8f8e325a"),
                            GameId = new Guid("f2932938-3b6d-45b9-8de0-f623a51c13e2"),
                            GameMoveId = 1,
                            PlayerId = new Guid("3054955c-8301-46c6-97ab-776108ef0a31"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("9347b306-a0bc-4079-a05f-186730cc4a4e"),
                            GameId = new Guid("f2932938-3b6d-45b9-8de0-f623a51c13e2"),
                            GameMoveId = 2,
                            PlayerId = new Guid("3054955c-8301-46c6-97ab-776108ef0a31"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("3b9282bd-6ed8-415e-964c-3f9bb15693ff"),
                            GameId = new Guid("f2932938-3b6d-45b9-8de0-f623a51c13e2"),
                            GameMoveId = 3,
                            PlayerId = new Guid("3054955c-8301-46c6-97ab-776108ef0a31"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__tblPlaye__3214EC0786DA1BDC");

                    b.ToTable("tblPlayer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3054955c-8301-46c6-97ab-776108ef0a31"),
                            Email = "123@gmail.com",
                            Password = "W6ph5Mm5Pz8GgiULbPgzG37mj9g=",
                            UserName = "Sh1PD3STR0Y3R"
                        },
                        new
                        {
                            Id = new Guid("f730d22c-1ad2-452c-92cc-d82ce3826c41"),
                            Email = "456@gmail.com",
                            Password = "YRfkWrV/hmDYZqIcpenSwx28GUU=",
                            UserName = "Timmy"
                        },
                        new
                        {
                            Id = new Guid("b2367ccb-adf4-418a-9c8b-67b24ce6c968"),
                            Email = "789@yahoo.com",
                            Password = "7DUut/wAuxmp4mKiKKNr9eEUeG0=",
                            UserName = "LoveMyCats1155"
                        },
                        new
                        {
                            Id = new Guid("337455fa-8b86-44b3-9086-0aae72e9c108"),
                            Email = "aaabbb@amazon.com",
                            Password = "3oUt/zAHVa53n7yyDzprXz4Rxs8=",
                            UserName = "Skeert"
                        },
                        new
                        {
                            Id = new Guid("37c04a2d-c484-4dcb-ae0a-8500ad8c566a"),
                            Email = "uTest@yahoo.com",
                            Password = "qUqP5cyxm6YcTAhz05Hph5gvu9M=",
                            UserName = "uTest"
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblChatHistory", b =>
                {
                    b.HasOne("HiddenBattleship.PL.Entities.tblGame", "Game")
                        .WithMany("tblChatHistories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiddenBattleship.PL.Entities.tblPlayer", "Player")
                        .WithMany("tblChatHistories")
                        .HasForeignKey("Receiver")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGame", b =>
                {
                    b.HasOne("HiddenBattleship.PL.Entities.tblPlayer", "Player")
                        .WithMany("tblGames")
                        .HasForeignKey("LoserId")
                        .IsRequired();

                    b.HasOne("HiddenBattleship.PL.Entities.tblChatHistory", null)
                        .WithMany("tblGames")
                        .HasForeignKey("tblChatHistoryId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGameMove", b =>
                {
                    b.HasOne("HiddenBattleship.PL.Entities.tblGame", "Game")
                        .WithMany("tblGameMoves")
                        .HasForeignKey("GameId")
                        .IsRequired();

                    b.HasOne("HiddenBattleship.PL.Entities.tblPlayer", "Player")
                        .WithMany("tblGameMoves")
                        .HasForeignKey("PlayerId")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblChatHistory", b =>
                {
                    b.Navigation("tblGames");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGame", b =>
                {
                    b.Navigation("tblChatHistories");

                    b.Navigation("tblGameMoves");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblPlayer", b =>
                {
                    b.Navigation("tblChatHistories");

                    b.Navigation("tblGameMoves");

                    b.Navigation("tblGames");
                });
#pragma warning restore 612, 618
        }
    }
}
