// <auto-generated />
using System;
using HiddenBattleship.PL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiddenBattleship.PL.Migrations
{
    [DbContext(typeof(HiddenBattleshipEntities))]
    partial class HiddenBattleshipEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblChatHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChatHistoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("Receiver")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Sender")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Timestamp")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__tblChatH__3214EC07CBD56E82");

                    b.HasIndex("GameId");

                    b.HasIndex("Receiver");

                    b.ToTable("tblChatHistory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2103257d-052b-4f73-a821-b3284d74c637"),
                            ChatHistoryId = 0,
                            GameId = new Guid("28439070-31c4-4ec3-a607-1212cf0ec963"),
                            Message = "1v1 me",
                            Receiver = new Guid("f256f0a0-d837-4322-8f7d-123aab1808d1"),
                            Sender = new Guid("aa6e32e1-9944-4e8d-be60-6369e5ae469f"),
                            Timestamp = new TimeSpan(0, 4, 10, 55, 0)
                        },
                        new
                        {
                            Id = new Guid("f2cc3b42-c6c2-4318-8227-93b2e87b0480"),
                            ChatHistoryId = 1,
                            GameId = new Guid("28439070-31c4-4ec3-a607-1212cf0ec963"),
                            Message = "You missed, LOL",
                            Receiver = new Guid("aa6e32e1-9944-4e8d-be60-6369e5ae469f"),
                            Sender = new Guid("f256f0a0-d837-4322-8f7d-123aab1808d1"),
                            Timestamp = new TimeSpan(0, 5, 1, 20, 0)
                        },
                        new
                        {
                            Id = new Guid("46d55afe-0ce5-48e3-81ff-df3ef850ded9"),
                            ChatHistoryId = 2,
                            GameId = new Guid("400442b7-459b-478d-a4b8-ffc84513fc5e"),
                            Message = "Follow my twitch stream?",
                            Receiver = new Guid("c01f71d6-3314-4e8e-a256-0ae4c6bcf48b"),
                            Sender = new Guid("f256f0a0-d837-4322-8f7d-123aab1808d1"),
                            Timestamp = new TimeSpan(0, 11, 51, 14, 0)
                        },
                        new
                        {
                            Id = new Guid("c463ade9-b99e-4ae8-83b3-c7274766ec53"),
                            ChatHistoryId = 3,
                            GameId = new Guid("e86c7bd4-26be-4f4f-ab94-c3054c368865"),
                            Message = "You're hacking, i'm telling my dad he works at Jagex!!11!",
                            Receiver = new Guid("aa6e32e1-9944-4e8d-be60-6369e5ae469f"),
                            Sender = new Guid("c01f71d6-3314-4e8e-a256-0ae4c6bcf48b"),
                            Timestamp = new TimeSpan(0, 1, 28, 19, 0)
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("IsOver")
                        .HasColumnType("int");

                    b.Property<Guid>("LoserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Player1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Player2")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("tblChatHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__tblGame__3214EC07DA24F9C4");

                    b.HasIndex("LoserId");

                    b.HasIndex("tblChatHistoryId");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("28439070-31c4-4ec3-a607-1212cf0ec963"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 0,
                            IsOver = 0,
                            LoserId = new Guid("f256f0a0-d837-4322-8f7d-123aab1808d1"),
                            Player1 = new Guid("e9d93fa9-8a2d-45b1-b211-b3f7fb4ffbf8"),
                            Player2 = new Guid("f256f0a0-d837-4322-8f7d-123aab1808d1"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("e9d93fa9-8a2d-45b1-b211-b3f7fb4ffbf8")
                        },
                        new
                        {
                            Id = new Guid("400442b7-459b-478d-a4b8-ffc84513fc5e"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 0,
                            IsOver = 0,
                            LoserId = new Guid("f256f0a0-d837-4322-8f7d-123aab1808d1"),
                            Player1 = new Guid("e9d93fa9-8a2d-45b1-b211-b3f7fb4ffbf8"),
                            Player2 = new Guid("f256f0a0-d837-4322-8f7d-123aab1808d1"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("e9d93fa9-8a2d-45b1-b211-b3f7fb4ffbf8")
                        },
                        new
                        {
                            Id = new Guid("e86c7bd4-26be-4f4f-ab94-c3054c368865"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 0,
                            IsOver = 0,
                            LoserId = new Guid("f256f0a0-d837-4322-8f7d-123aab1808d1"),
                            Player1 = new Guid("e9d93fa9-8a2d-45b1-b211-b3f7fb4ffbf8"),
                            Player2 = new Guid("f256f0a0-d837-4322-8f7d-123aab1808d1"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("e9d93fa9-8a2d-45b1-b211-b3f7fb4ffbf8")
                        },
                        new
                        {
                            Id = new Guid("d5971a87-2fac-4a85-82bd-bf94e30dad66"),
                            EndTime = new TimeSpan(0, 1, 20, 30, 0),
                            GameId = 0,
                            IsOver = 0,
                            LoserId = new Guid("f256f0a0-d837-4322-8f7d-123aab1808d1"),
                            Player1 = new Guid("e9d93fa9-8a2d-45b1-b211-b3f7fb4ffbf8"),
                            Player2 = new Guid("f256f0a0-d837-4322-8f7d-123aab1808d1"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("e9d93fa9-8a2d-45b1-b211-b3f7fb4ffbf8")
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGameMove", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GameMoveId")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetCoordinates")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeSpan>("TimeStamp")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__tblGameM__3214EC07B921B560");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tblGameMove", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f11d9b6-edc7-4fa6-a394-d61cd6372fe1"),
                            GameId = new Guid("28439070-31c4-4ec3-a607-1212cf0ec963"),
                            GameMoveId = 0,
                            PlayerId = new Guid("e9d93fa9-8a2d-45b1-b211-b3f7fb4ffbf8"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("95965e01-e40e-4a6a-b537-767e4c99f5db"),
                            GameId = new Guid("28439070-31c4-4ec3-a607-1212cf0ec963"),
                            GameMoveId = 1,
                            PlayerId = new Guid("e9d93fa9-8a2d-45b1-b211-b3f7fb4ffbf8"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("1a82c5f4-adfc-48cf-85b0-6272cd5ae1e2"),
                            GameId = new Guid("28439070-31c4-4ec3-a607-1212cf0ec963"),
                            GameMoveId = 2,
                            PlayerId = new Guid("e9d93fa9-8a2d-45b1-b211-b3f7fb4ffbf8"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("b3423e72-1575-4874-8374-0f26b1ed1ab1"),
                            GameId = new Guid("28439070-31c4-4ec3-a607-1212cf0ec963"),
                            GameMoveId = 3,
                            PlayerId = new Guid("e9d93fa9-8a2d-45b1-b211-b3f7fb4ffbf8"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__tblPlaye__3214EC0786DA1BDC");

                    b.ToTable("tblPlayer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9d93fa9-8a2d-45b1-b211-b3f7fb4ffbf8"),
                            Email = "123@gmail.com",
                            Password = "W6ph5Mm5Pz8GgiULbPgzG37mj9g=",
                            UserName = "Sh1PD3STR0Y3R"
                        },
                        new
                        {
                            Id = new Guid("f256f0a0-d837-4322-8f7d-123aab1808d1"),
                            Email = "456@gmail.com",
                            Password = "YRfkWrV/hmDYZqIcpenSwx28GUU=",
                            UserName = "Timmy"
                        },
                        new
                        {
                            Id = new Guid("c01f71d6-3314-4e8e-a256-0ae4c6bcf48b"),
                            Email = "789@yahoo.com",
                            Password = "7DUut/wAuxmp4mKiKKNr9eEUeG0=",
                            UserName = "LoveMyCats1155"
                        },
                        new
                        {
                            Id = new Guid("aa6e32e1-9944-4e8d-be60-6369e5ae469f"),
                            Email = "aaabbb@amazon.com",
                            Password = "3oUt/zAHVa53n7yyDzprXz4Rxs8=",
                            UserName = "Skeert"
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblChatHistory", b =>
                {
                    b.HasOne("HiddenBattleship.PL.Entities.tblGame", "Game")
                        .WithMany("tblChatHistories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiddenBattleship.PL.Entities.tblPlayer", "Player")
                        .WithMany("tblChatHistories")
                        .HasForeignKey("Receiver")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGame", b =>
                {
                    b.HasOne("HiddenBattleship.PL.Entities.tblPlayer", "Player")
                        .WithMany("tblGames")
                        .HasForeignKey("LoserId")
                        .IsRequired();

                    b.HasOne("HiddenBattleship.PL.Entities.tblChatHistory", null)
                        .WithMany("tblGames")
                        .HasForeignKey("tblChatHistoryId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGameMove", b =>
                {
                    b.HasOne("HiddenBattleship.PL.Entities.tblGame", "Game")
                        .WithMany("tblGameMoves")
                        .HasForeignKey("GameId")
                        .IsRequired();

                    b.HasOne("HiddenBattleship.PL.Entities.tblPlayer", "Player")
                        .WithMany("tblGameMoves")
                        .HasForeignKey("PlayerId")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblChatHistory", b =>
                {
                    b.Navigation("tblGames");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGame", b =>
                {
                    b.Navigation("tblChatHistories");

                    b.Navigation("tblGameMoves");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblPlayer", b =>
                {
                    b.Navigation("tblChatHistories");

                    b.Navigation("tblGameMoves");

                    b.Navigation("tblGames");
                });
#pragma warning restore 612, 618
        }
    }
}
