// <auto-generated />
using System;
using HiddenBattleship.PL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiddenBattleship.PL.Migrations
{
    [DbContext(typeof(HiddenBattleshipEntities))]
    partial class HiddenBattleshipEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblChatHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChatHistoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("Receiver")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Sender")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Timestamp")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__tblChatH__3214EC07CBD56E82");

                    b.HasIndex("GameId");

                    b.HasIndex("Receiver");

                    b.ToTable("tblChatHistory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10083e34-f4eb-4eb8-9f09-abfe2ee00eb3"),
                            ChatHistoryId = 1,
                            GameId = new Guid("0dcf22df-5679-4656-805d-f9619103802f"),
                            Message = "1v1 me",
                            Receiver = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Sender = new Guid("e6f5d410-7877-4798-b90a-d1934ea55817"),
                            Timestamp = new TimeSpan(0, 4, 10, 55, 0)
                        },
                        new
                        {
                            Id = new Guid("e09e062b-9b48-41bb-9cdd-18543814eecb"),
                            ChatHistoryId = 1,
                            GameId = new Guid("0dcf22df-5679-4656-805d-f9619103802f"),
                            Message = "You missed, LOL",
                            Receiver = new Guid("e6f5d410-7877-4798-b90a-d1934ea55817"),
                            Sender = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Timestamp = new TimeSpan(0, 5, 1, 20, 0)
                        },
                        new
                        {
                            Id = new Guid("a2ebdec4-7275-4028-bcb1-b3a036971d6a"),
                            ChatHistoryId = 1,
                            GameId = new Guid("0dcf22df-5679-4656-805d-f9619103802f"),
                            Message = "Follow my twitch stream?",
                            Receiver = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Sender = new Guid("e6f5d410-7877-4798-b90a-d1934ea55817"),
                            Timestamp = new TimeSpan(0, 11, 51, 14, 0)
                        },
                        new
                        {
                            Id = new Guid("02cc8c67-b2de-4020-a111-90b48337bde8"),
                            ChatHistoryId = 1,
                            GameId = new Guid("0dcf22df-5679-4656-805d-f9619103802f"),
                            Message = "You're hacking, i'm telling my dad he works at Jagex!!11!",
                            Receiver = new Guid("e6f5d410-7877-4798-b90a-d1934ea55817"),
                            Sender = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Timestamp = new TimeSpan(0, 1, 28, 19, 0)
                        },
                        new
                        {
                            Id = new Guid("86f3db31-377a-4422-b0c7-fbab856e17af"),
                            ChatHistoryId = 2,
                            GameId = new Guid("9b2d4276-570a-44b0-bf19-f6c52bebb115"),
                            Message = "1v1 me",
                            Receiver = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Sender = new Guid("d443d28c-97cd-41a4-b297-9afff57d58c4"),
                            Timestamp = new TimeSpan(0, 4, 10, 55, 0)
                        },
                        new
                        {
                            Id = new Guid("e9bc2e29-83da-4634-ba57-fd8a06e8132e"),
                            ChatHistoryId = 2,
                            GameId = new Guid("9b2d4276-570a-44b0-bf19-f6c52bebb115"),
                            Message = "You missed, LOL",
                            Receiver = new Guid("d443d28c-97cd-41a4-b297-9afff57d58c4"),
                            Sender = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Timestamp = new TimeSpan(0, 5, 1, 20, 0)
                        },
                        new
                        {
                            Id = new Guid("93358209-c8c7-427d-a3b7-bbde753c4c38"),
                            ChatHistoryId = 2,
                            GameId = new Guid("9b2d4276-570a-44b0-bf19-f6c52bebb115"),
                            Message = "Follow my twitch stream?",
                            Receiver = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Sender = new Guid("d443d28c-97cd-41a4-b297-9afff57d58c4"),
                            Timestamp = new TimeSpan(0, 11, 51, 14, 0)
                        },
                        new
                        {
                            Id = new Guid("6d9a37db-97e3-40ed-9526-b6a0dc576b91"),
                            ChatHistoryId = 2,
                            GameId = new Guid("9b2d4276-570a-44b0-bf19-f6c52bebb115"),
                            Message = "You're hacking, i'm telling my dad he works at Jagex!!11!",
                            Receiver = new Guid("d443d28c-97cd-41a4-b297-9afff57d58c4"),
                            Sender = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Timestamp = new TimeSpan(0, 1, 28, 19, 0)
                        },
                        new
                        {
                            Id = new Guid("af44a1ed-b641-409d-bb88-1a1951c00056"),
                            ChatHistoryId = 3,
                            GameId = new Guid("2c88036e-1494-49e1-b929-e49a456ca384"),
                            Message = "1v1 me",
                            Receiver = new Guid("1ec34753-526c-4ccb-bd97-331d4912e519"),
                            Sender = new Guid("1ec34753-526c-4ccb-bd97-331d4912e519"),
                            Timestamp = new TimeSpan(0, 4, 10, 55, 0)
                        },
                        new
                        {
                            Id = new Guid("e31c401e-78a5-4e10-8a2a-ba869057a1ea"),
                            ChatHistoryId = 3,
                            GameId = new Guid("2c88036e-1494-49e1-b929-e49a456ca384"),
                            Message = "You missed, LOL",
                            Receiver = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Sender = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Timestamp = new TimeSpan(0, 5, 1, 20, 0)
                        },
                        new
                        {
                            Id = new Guid("447856bd-e6b7-4cd2-b0f5-40ad2aefc643"),
                            ChatHistoryId = 3,
                            GameId = new Guid("2c88036e-1494-49e1-b929-e49a456ca384"),
                            Message = "Follow my twitch stream?",
                            Receiver = new Guid("1ec34753-526c-4ccb-bd97-331d4912e519"),
                            Sender = new Guid("1ec34753-526c-4ccb-bd97-331d4912e519"),
                            Timestamp = new TimeSpan(0, 11, 51, 14, 0)
                        },
                        new
                        {
                            Id = new Guid("f8dc4185-5655-41c8-aad4-5d14f69585b2"),
                            ChatHistoryId = 3,
                            GameId = new Guid("2c88036e-1494-49e1-b929-e49a456ca384"),
                            Message = "You're hacking, i'm telling my dad he works at Jagex!!11!",
                            Receiver = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Sender = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Timestamp = new TimeSpan(0, 1, 28, 19, 0)
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("EndTime")
                        .IsRequired()
                        .HasColumnType("time");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOver")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LoserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Player1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Player2")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("tblChatHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__tblGame__3214EC07DA24F9C4");

                    b.HasIndex("LoserId");

                    b.HasIndex("tblChatHistoryId");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0dcf22df-5679-4656-805d-f9619103802f"),
                            EndTime = new TimeSpan(0, 1, 11, 30, 0),
                            GameId = 0,
                            IsOver = true,
                            LoserId = new Guid("e6f5d410-7877-4798-b90a-d1934ea55817"),
                            Player1 = new Guid("1ec34753-526c-4ccb-bd97-331d4912e519"),
                            Player2 = new Guid("e6f5d410-7877-4798-b90a-d1934ea55817"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("1ec34753-526c-4ccb-bd97-331d4912e519")
                        },
                        new
                        {
                            Id = new Guid("9b2d4276-570a-44b0-bf19-f6c52bebb115"),
                            EndTime = new TimeSpan(0, 2, 20, 30, 0),
                            GameId = 1,
                            IsOver = false,
                            LoserId = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Player1 = new Guid("1ec34753-526c-4ccb-bd97-331d4912e519"),
                            Player2 = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            StartTime = new TimeSpan(0, 2, 21, 31, 0),
                            WinnerId = new Guid("8d520d13-a349-471f-9998-0743604ef4bc")
                        },
                        new
                        {
                            Id = new Guid("2c88036e-1494-49e1-b929-e49a456ca384"),
                            EndTime = new TimeSpan(0, 3, 20, 30, 0),
                            GameId = 2,
                            IsOver = false,
                            LoserId = new Guid("d443d28c-97cd-41a4-b297-9afff57d58c4"),
                            Player1 = new Guid("1ec34753-526c-4ccb-bd97-331d4912e519"),
                            Player2 = new Guid("d443d28c-97cd-41a4-b297-9afff57d58c4"),
                            StartTime = new TimeSpan(0, 1, 22, 32, 0),
                            WinnerId = new Guid("1ec34753-526c-4ccb-bd97-331d4912e519")
                        },
                        new
                        {
                            Id = new Guid("2e448797-7627-4a85-9aaf-a8436edd320e"),
                            EndTime = new TimeSpan(0, 4, 20, 30, 0),
                            GameId = 3,
                            IsOver = false,
                            LoserId = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Player1 = new Guid("e6f5d410-7877-4798-b90a-d1934ea55817"),
                            Player2 = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("e6f5d410-7877-4798-b90a-d1934ea55817")
                        },
                        new
                        {
                            Id = new Guid("c44a09b3-010c-4cf0-8e24-7fe746c4ebd8"),
                            EndTime = new TimeSpan(0, 5, 20, 30, 0),
                            GameId = 4,
                            IsOver = true,
                            LoserId = new Guid("d443d28c-97cd-41a4-b297-9afff57d58c4"),
                            Player1 = new Guid("e6f5d410-7877-4798-b90a-d1934ea55817"),
                            Player2 = new Guid("d443d28c-97cd-41a4-b297-9afff57d58c4"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("e6f5d410-7877-4798-b90a-d1934ea55817")
                        },
                        new
                        {
                            Id = new Guid("01d195d0-4a11-460c-93c5-747b3c9ae47c"),
                            EndTime = new TimeSpan(0, 6, 20, 30, 0),
                            GameId = 5,
                            IsOver = false,
                            LoserId = new Guid("d443d28c-97cd-41a4-b297-9afff57d58c4"),
                            Player1 = new Guid("e6f5d410-7877-4798-b90a-d1934ea55817"),
                            Player2 = new Guid("d443d28c-97cd-41a4-b297-9afff57d58c4"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("e6f5d410-7877-4798-b90a-d1934ea55817")
                        },
                        new
                        {
                            Id = new Guid("242a0d3a-c8a5-4696-840a-c92f73068e4c"),
                            EndTime = new TimeSpan(0, 7, 20, 30, 0),
                            GameId = 6,
                            IsOver = false,
                            LoserId = new Guid("d443d28c-97cd-41a4-b297-9afff57d58c4"),
                            Player1 = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Player2 = new Guid("d443d28c-97cd-41a4-b297-9afff57d58c4"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("8d520d13-a349-471f-9998-0743604ef4bc")
                        },
                        new
                        {
                            Id = new Guid("a5202682-3cdb-4f63-8cc2-9d661b9a720f"),
                            EndTime = new TimeSpan(0, 8, 20, 30, 0),
                            GameId = 7,
                            IsOver = false,
                            LoserId = new Guid("d443d28c-97cd-41a4-b297-9afff57d58c4"),
                            Player1 = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Player2 = new Guid("d443d28c-97cd-41a4-b297-9afff57d58c4"),
                            StartTime = new TimeSpan(0, 1, 20, 30, 0),
                            WinnerId = new Guid("8d520d13-a349-471f-9998-0743604ef4bc")
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGameMove", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GameMoveId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHit")
                        .HasColumnType("bit");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetCoordinates")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeSpan>("TimeStamp")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__tblGameM__3214EC07B921B560");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tblGameMove", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a408bcf-c82f-47a2-8cf3-30f8403e3dab"),
                            GameId = new Guid("0dcf22df-5679-4656-805d-f9619103802f"),
                            GameMoveId = 0,
                            IsHit = true,
                            PlayerId = new Guid("1ec34753-526c-4ccb-bd97-331d4912e519"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("c5512b58-7423-48c0-9a92-708115e7eb37"),
                            GameId = new Guid("0dcf22df-5679-4656-805d-f9619103802f"),
                            GameMoveId = 1,
                            IsHit = true,
                            PlayerId = new Guid("1ec34753-526c-4ccb-bd97-331d4912e519"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("7a52dd76-9968-4f90-9ec6-d74a396fc978"),
                            GameId = new Guid("0dcf22df-5679-4656-805d-f9619103802f"),
                            GameMoveId = 2,
                            IsHit = true,
                            PlayerId = new Guid("1ec34753-526c-4ccb-bd97-331d4912e519"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        },
                        new
                        {
                            Id = new Guid("59c277e0-6647-4f26-b089-fea83580a717"),
                            GameId = new Guid("0dcf22df-5679-4656-805d-f9619103802f"),
                            GameMoveId = 3,
                            IsHit = true,
                            PlayerId = new Guid("1ec34753-526c-4ccb-bd97-331d4912e519"),
                            TargetCoordinates = "A5",
                            TimeStamp = new TimeSpan(0, 1, 20, 30, 0)
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__tblPlaye__3214EC0786DA1BDC");

                    b.ToTable("tblPlayer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ec34753-526c-4ccb-bd97-331d4912e519"),
                            Email = "123@gmail.com",
                            Password = "W6ph5Mm5Pz8GgiULbPgzG37mj9g=",
                            UserName = "Sh1PD3STR0Y3R"
                        },
                        new
                        {
                            Id = new Guid("e6f5d410-7877-4798-b90a-d1934ea55817"),
                            Email = "456@gmail.com",
                            Password = "YRfkWrV/hmDYZqIcpenSwx28GUU=",
                            UserName = "Timmy"
                        },
                        new
                        {
                            Id = new Guid("8d520d13-a349-471f-9998-0743604ef4bc"),
                            Email = "789@yahoo.com",
                            Password = "7DUut/wAuxmp4mKiKKNr9eEUeG0=",
                            UserName = "LoveMyCats1155"
                        },
                        new
                        {
                            Id = new Guid("d443d28c-97cd-41a4-b297-9afff57d58c4"),
                            Email = "aaabbb@amazon.com",
                            Password = "3oUt/zAHVa53n7yyDzprXz4Rxs8=",
                            UserName = "Skeert"
                        },
                        new
                        {
                            Id = new Guid("d03a3240-744b-4851-aca3-dd931e88ee23"),
                            Email = "uTest@yahoo.com",
                            Password = "qUqP5cyxm6YcTAhz05Hph5gvu9M=",
                            UserName = "uTest"
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblShip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ShipType")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblShip");

                    b.ToTable("tblShip", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("82ac0e17-4a91-4040-8e8f-15a3065a36f7"),
                            ShipType = 0,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("9b82dd7f-07af-4ff2-a882-40512c05dd9c"),
                            ShipType = 4,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("358f1a8a-d620-4c95-a4c8-9582762a1dd9"),
                            ShipType = 1,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("7bd24bab-35b4-4b19-ab44-ea2138dcfe3a"),
                            ShipType = 2,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("c355a5d3-8067-4ea9-879b-5c066902c842"),
                            ShipType = 3,
                            Size = 2
                        });
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblChatHistory", b =>
                {
                    b.HasOne("HiddenBattleship.PL.Entities.tblGame", "Game")
                        .WithMany("tblChatHistories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiddenBattleship.PL.Entities.tblPlayer", "Player")
                        .WithMany("tblChatHistories")
                        .HasForeignKey("Receiver")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGame", b =>
                {
                    b.HasOne("HiddenBattleship.PL.Entities.tblPlayer", "Player")
                        .WithMany("tblGames")
                        .HasForeignKey("LoserId");

                    b.HasOne("HiddenBattleship.PL.Entities.tblChatHistory", null)
                        .WithMany("tblGames")
                        .HasForeignKey("tblChatHistoryId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGameMove", b =>
                {
                    b.HasOne("HiddenBattleship.PL.Entities.tblGame", "Game")
                        .WithMany("tblGameMoves")
                        .HasForeignKey("GameId")
                        .IsRequired();

                    b.HasOne("HiddenBattleship.PL.Entities.tblPlayer", "Player")
                        .WithMany("tblGameMoves")
                        .HasForeignKey("PlayerId")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblChatHistory", b =>
                {
                    b.Navigation("tblGames");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblGame", b =>
                {
                    b.Navigation("tblChatHistories");

                    b.Navigation("tblGameMoves");
                });

            modelBuilder.Entity("HiddenBattleship.PL.Entities.tblPlayer", b =>
                {
                    b.Navigation("tblChatHistories");

                    b.Navigation("tblGameMoves");

                    b.Navigation("tblGames");
                });
#pragma warning restore 612, 618
        }
    }
}
